# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-30 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0005_auto_20180329_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='mess_pro', to='pong.User'),
            preserve_default=False,
        ),
    ]
